-- 1. Create the new tables if they don't exist
CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL UNIQUE,
    price NUMERIC DEFAULT 0,
    category TEXT
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    item_name TEXT NOT NULL,
    quantity INTEGER DEFAULT 1,
    price NUMERIC DEFAULT 0,
    total NUMERIC DEFAULT 0
);

-- 2. Modify existing 'orders' table to support the new flow
-- We relax the NOT NULL constraint on 'order_type' so it can be optional or removed later
ALTER TABLE public.orders ALTER COLUMN order_type DROP NOT NULL;

-- 3. Add any missing columns to 'orders' if they aren't there
-- (total_amount, payment_status usually exist, but just in case)
-- ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS invoice_number TEXT;

-- 4. Enable RLS on new tables
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- 5. Policies for new tables
CREATE POLICY "Enable all access for all users" ON public.menu_items FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON public.order_items FOR ALL TO public USING (true) WITH CHECK (true);
