-- Create menu_items table (replacing orderTypes)
CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL UNIQUE,
    price NUMERIC DEFAULT 0,
    category TEXT
);

-- Create orders table (Refactored)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    total_amount NUMERIC DEFAULT 0,
    payment_status TEXT DEFAULT 'Not Paid', -- 'Not Paid', 'Paid'
    client_name TEXT NOT NULL,
    client_phone TEXT,
    notes TEXT,
    -- Removed: deadline (Serve Date), amount_paid (Initial Payment), remaining_balance (Logic simplified to Paid/Not Paid)
    -- We can keep payment tracking if needed, but per request simplifying to Total Cost.
    -- For now, if payment_status is 'Paid', we assume full amount is paid.
    invoice_number TEXT -- Storing simple invoice number here or in invoices table
);

-- Create order_items table (Linking items to orders)
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    item_name TEXT NOT NULL, -- Copying name to preserve history if menu item changes
    quantity INTEGER DEFAULT 1,
    price NUMERIC DEFAULT 0, -- Price at time of order
    total NUMERIC DEFAULT 0 -- quantity * price
);

-- Create invoices table (Optional if we just use orders, but keeping for generated snapshots)
CREATE TABLE IF NOT EXISTS public.invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    invoice_number TEXT NOT NULL,
    total_amount NUMERIC DEFAULT 0,
    issue_date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'pending'
);

-- Set permissions
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable all access for all users" ON public.menu_items FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON public.orders FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON public.order_items FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON public.invoices FOR ALL TO public USING (true) WITH CHECK (true);
